<?php

namespace app\service;

use app\model\User;

class ExportService
{
    public function exportToPng(array $data, string $filename, int $userId): string
    {
        $user = User::find($userId);
        $username = $user ? $user->username : 'Unknown';
        $timestamp = date('Y-m-d H:i:s');

        $width = 800;
        $height = 600;
        $image = imagecreatetruecolor($width, $height);

        $white = imagecolorallocate($image, 255, 255, 255);
        $gray = imagecolorallocate($image, 200, 200, 200);
        
        imagefill($image, 0, 0, $white);
        imagestring($image, 5, 10, 10, "CampusOps Export", $gray);
        imagestring($image, 3, 10, $height - 40, "Exported by: {$username}", $gray);
        imagestring($image, 3, 10, $height - 25, "Timestamp: {$timestamp}", $gray);

        foreach ($data as $key => $value) {
            imagestring($image, 4, 50, 50 + ($key * 20), "{$key}: {$value}", $gray);
        }

        $filepath = runtime_path() . '/exports/' . $filename . '_' . $userId . '_' . time() . '.png';
        if (!is_dir(dirname($filepath))) {
            mkdir(dirname($filepath), 0755, true);
        }

        imagepng($image, $filepath);
        imagedestroy($image);

        return $filepath;
    }

    public function exportToPdf(array $data, string $filename, int $userId): string
    {
        $user = User::find($userId);
        $username = $user ? $user->username : 'Unknown';
        $timestamp = date('Y-m-d H:i:s');

        $content = '<html><head><style>body{font-family:Arial;}</style></head><body>';
        $content .= '<div style="position:fixed;bottom:50px;left:50px;transform:rotate(-45deg);opacity:0.1;font-size:48px;">';
        $content .= "CampusOps - {$username} - {$timestamp}";
        $content .= '</div>';
        
        $content .= '<h1>CampusOps Export</h1>';
        $content .= '<table border="1" cellpadding="5" style="border-collapse:collapse;">';
        foreach ($data as $key => $value) {
            $content .= '<tr><th>' . htmlspecialchars($key) . '</th><td>' . htmlspecialchars($value) . '</td></tr>';
        }
        $content .= '</table>';
        
        $content .= '<div style="margin-top:50px;font-size:12px;color:#666;">';
        $content .= "Exported by: {$username} | Timestamp: {$timestamp}";
        $content .= '</div>';
        $content .= '</body></html>';

        $filepath = runtime_path() . '/exports/' . $filename . '_' . $userId . '_' . time() . '.html';
        if (!is_dir(dirname($filepath))) {
            mkdir(dirname($filepath), 0755, true);
        }

        file_put_contents($filepath, $content);

        return $filepath;
    }

    public function exportToExcel(array $data, string $filename, int $userId): string
    {
        $user = User::find($userId);
        $username = $user ? $user->username : 'Unknown';
        $timestamp = date('Y-m-d H:i:s');

        $csv = "CampusOps Export\n";
        $csv .= "Generated by: {$username}\n";
        $csv .= "Timestamp: {$timestamp}\n\n";

        foreach ($data as $row) {
            $csv .= implode(',', array_map(function($v) {
                return '"' . str_replace('"', '""', $v) . '"';
            }, $row)) . "\n";
        }

        $csv .= "\nExported from CampusOps | {$username} | {$timestamp}\n";

        $filepath = runtime_path() . '/exports/' . $filename . '_' . $userId . '_' . time() . '.csv';
        if (!is_dir(dirname($filepath))) {
            mkdir(dirname($filepath), 0755, true);
        }

        file_put_contents($filepath, $csv);

        return $filepath;
    }

    public function getWatermarkText(int $userId): string
    {
        $user = User::find($userId);
        if (!$user) {
            return 'CampusOps';
        }
        return "CampusOps - {$user->username} - " . date('Y-m-d H:i:s');
    }
}